import { StyleSheet } from "react-native";
import { theme } from "../../lib/theme";

export const homeLandingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#061418",
  },
  flex: {
    flex: 1,
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.ivory,
  },
  heroBackdrop: {
    backgroundColor: "#061418",
  },
  topVignette: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 220,
  },
  topVignetteBand: {
    flex: 1,
    backgroundColor: "#000",
  },
  bottomVignette: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 340,
  },
  bottomVignetteBand: {
    flex: 1,
    backgroundColor: "#000",
  },
  wordmarkRow: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    left: 36,
    zIndex: 20,
  },
  wordmarkDark: {
    color: "#0B1F3A",
    fontSize: 26,
    fontWeight: "700",
    letterSpacing: 3.5,
  },
  wordmarkAccent: {
    color: "#27C9C3",
    fontSize: 26,
    fontWeight: "700",
    letterSpacing: 3.5,
  },
  welcomeOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 6,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    backgroundColor: "rgba(6,20,24,0.42)",
  },
  welcomeCard: {
    maxWidth: 340,
    alignItems: "center",
  },
  welcomeGreeting: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  welcomeTitle: {
    marginTop: 10,
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: -0.8,
    textAlign: "center",
  },
  welcomeBody: {
    marginTop: 12,
    color: "rgba(255,255,255,0.9)",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
    textAlign: "center",
  },
  indicatorsDock: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 3,
  },
  dotsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  dot: {
    height: 5,
    borderRadius: 999,
  },
  dotActive: {
    width: 18,
    backgroundColor: "rgba(255,255,255,0.96)",
  },
  dotIdle: {
    width: 5,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  promotionOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    paddingHorizontal: 24,
    paddingBottom: 28,
  },
  promotionBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(0,194,184,0.92)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 12,
  },
  promotionBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  promotionTitle: {
    color: "#fff",
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  promotionSubtitle: {
    marginTop: 8,
    color: "rgba(255,255,255,0.9)",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
    maxWidth: "92%",
  },
  promotionCtaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 18,
  },
  promotionCtaPrimary: {
    backgroundColor: theme.colors.turquoise,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  promotionCtaSecondary: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  promotionCtaTextPrimary: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
  },
  promotionCtaTextSecondary: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  loginDock: {
    paddingHorizontal: 22,
    paddingTop: 10,
    zIndex: 5,
  },
  loginOverlayCard: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    shadowColor: "#0B2B33",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  inputRow: {
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(226,232,240,0.95)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  inputRowSecond: {
    marginTop: 8,
  },
  input: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: theme.colors.charcoal,
    paddingVertical: 0,
  },
  forgotPasswordLink: {
    alignSelf: "flex-end",
    marginTop: 8,
    marginBottom: 2,
  },
  forgotPasswordText: {
    color: theme.colors.turquoise,
    fontWeight: "800",
    fontSize: 12,
  },
  signInButton: {
    marginTop: 10,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.colors.turquoise,
    alignItems: "center",
    justifyContent: "center",
  },
  signInDisabled: {
    opacity: 0.75,
  },
  signInText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
  },
  footerLinksRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  footerPrimaryText: {
    color: theme.colors.turquoise,
    fontWeight: "800",
    fontSize: 13,
  },
  footerDivider: {
    color: theme.colors.muted,
    fontWeight: "700",
    fontSize: 13,
  },
  footerSecondaryText: {
    color: theme.colors.muted,
    fontWeight: "700",
    fontSize: 13,
  },
});
